### ISSUE TITLE
Disabled sites

### ISSUE THREAD

**Issue by honsa** [HOMMinteractive/hommxmlsitemap#3]
Thank you for your nice plugin.

Is there an option to exclude not enabled sites?

**Comment by ammannbe** [comment]
Seems that this is not possible at the moment with only disable a complete site.

I think the query which should be ajusted is here: https://github.com/HOMMinteractive/hommxmlsitemap/blob/c366bfb5972e08b7b5a03f24c7471d8240a0a7a9/src/controllers/SitemapController.php#L246

As far as I know theres an attribute `enabled` which can be queried, like:

```php
->where(['=', '[[elements_sites.enabled]]', true])
```

But I'm not sure and at the moment I have no time to test this. So if you want you can test it and create a PR. Otherwise you have to wait a little bit 😉

**Comment by honsa** [comment]
@ammannbe Yes that is true.  👍 

I made a pr to fix this issue:

https://github.com/HOMMinteractive/hommxmlsitemap/pull/4
